name: satcom
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - libexpat=2.7.4
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.11.14
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - flake8==7.3.0
      - fonttools==4.61.1
      - iniconfig==2.3.0
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mccabe==0.7.0
      - numpy==2.4.2
      - pandas==3.0.0
      - pillow==12.1.1
      - pluggy==1.6.0
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - scipy==1.17.0
      - six==1.17.0
      - tzdata==2025.3
