name: comp_vision
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.6.1=hf411b9b_1
  - pip=26.0.1=pyhc872135_0
  - python=3.9.25=h716150d_1
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - altair==5.5.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - autocorrect==2.6.1
      - blinker==1.9.0
      - cachetools==6.2.6
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - comtypes==1.4.15
      - contourpy==1.3.0
      - cryptography==46.0.5
      - cycler==0.12.1
      - deep-sort-realtime==1.3.2
      - easyocr==1.7.2
      - filelock==3.19.1
      - flatbuffers==25.12.19
      - fonttools==4.60.2
      - fsspec==2025.10.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.48.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.78.0
      - h5py==3.14.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==3.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mediapipe==0.10.14
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.1.0
      - narwhals==2.16.0
      - networkx==3.2.1
      - ninja==1.13.0
      - numpy==1.26.4
      - oauthlib==3.3.1
      - onnx==1.19.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==26.0
      - pandas==2.3.3
      - pillow==11.3.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - protobuf==4.25.8
      - psutil==7.2.2
      - pyarrow==21.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pyaudio==0.2.14
      - pyclipper==1.3.0.post6
      - pycparser==2.23
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pypiwin32==223
      - pytesseract==0.3.13
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - pyttsx3==2.99
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.3.2
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - setuptools==82.0.0
      - shapely==2.0.7
      - six==1.17.0
      - smmap==5.0.2
      - sounddevice==0.5.5
      - streamlit==1.50.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.16.1
      - tensorflow-estimator==2.10.0
      - tensorflow-intel==2.16.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - toml==0.10.2
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tornado==6.5.4
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - ultralytics==8.4.14
      - ultralytics-thop==2.0.18
      - urllib3==2.6.3
      - watchdog==6.0.0
      - werkzeug==3.1.5
      - wheel==0.46.3
      - wrapt==2.1.1
      - zipp==3.23.0
prefix: C:\Users\umair\.conda\envs\comp_vision
