name: base
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _anaconda_depends=2025.12=py313_mkl_0
  - aiobotocore=2.25.0=py313haa95532_0
  - aiodns=3.5.0=py313haa95532_1
  - aiohappyeyeballs=2.6.1=py313haa95532_0
  - aiohttp=3.13.2=py313h02ab6af_0
  - aioitertools=0.12.0=py313haa95532_0
  - aiosignal=1.4.0=py313haa95532_0
  - alabaster=0.7.16=py313haa95532_0
  - altair=5.5.0=py313haa95532_0
  - anaconda-anon-usage=0.7.5=pyhb46e38b_100
  - anaconda-auth=0.12.0=py313haa95532_0
  - anaconda-catalogs=0.2.0=py313haa95532_3
  - anaconda-cli-base=0.7.0=py313haa95532_0
  - anaconda-client=1.14.0=py313haa95532_0
  - anaconda-navigator=2.7.0=py313haa95532_1
  - anaconda-project=0.11.1=py313haa95532_1
  - anaconda_powershell_prompt=1.1.0=haa95532_1
  - anaconda_prompt=1.1.0=haa95532_1
  - annotated-types=0.6.0=py313haa95532_1
  - anyio=4.10.0=py313haa95532_0
  - aom=3.12.1=h00a0c3c_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - archspec=0.2.5=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py313h02ab6af_0
  - arrow=1.4.0=py313haa95532_0
  - arrow-cpp=21.0.0=h6358905_1
  - astroid=3.3.11=py313haa95532_0
  - astropy=7.1.1=py313h540bb41_0
  - astropy-iers-data=0.2025.11.10.0.38.31=py313haa95532_0
  - asttokens=3.0.0=py313haa95532_0
  - async-lru=2.0.5=py313haa95532_0
  - asyncssh=2.21.1=py313haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=25.4.0=py313haa95532_2
  - automat=24.8.1=py313haa95532_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - babel=2.17.0=py313haa95532_0
  - bcrypt=5.0.0=py313h114bc41_0
  - beautifulsoup4=4.13.5=py313haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=25.9.0=py313haa95532_0
  - blas=1.0=mkl
  - bleach=6.3.0=py313haa95532_0
  - blinker=1.9.0=py313haa95532_0
  - blosc=1.21.6=h4190f5b_0
  - bokeh=3.8.0=py313haa95532_0
  - boltons=25.0.0=py313haa95532_0
  - botocore=1.40.46=py313haa95532_0
  - bottleneck=1.4.2=py313h540bb41_1
  - brotlicffi=1.1.0.0=py313h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - c-blosc2=2.17.1=h0eb4811_0
  - ca-certificates=2025.11.4=haa95532_0
  - cachetools=5.5.1=py313haa95532_0
  - cairo=1.18.4=he9e932c_0
  - cattrs=25.3.0=py313hdf80283_0
  - certifi=2025.11.12=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - chardet=5.2.0=py313haa95532_0
  - charset-normalizer=3.4.4=py313haa95532_0
  - click=8.2.1=py313haa95532_0
  - cloudpickle=3.1.1=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - colorcet=3.1.0=py313haa95532_0
  - comm=0.2.3=py313haa95532_0
  - conda=25.11.0=py313haa95532_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313haa95532_1
  - conda-build=25.11.1=py313hcfce1f1_0
  - conda-content-trust=0.2.0=py313haa95532_1
  - conda-index=0.7.0=py313haa95532_0
  - conda-libmamba-solver=25.11.0=pyhdf14ebd_0
  - conda-pack=0.8.1=py313haa95532_0
  - conda-package-handling=2.4.0=py313haa95532_1
  - conda-package-streaming=0.12.0=py313haa95532_1
  - conda-repo-cli=1.0.173=py313haa95532_0
  - constantly=23.10.4=py313haa95532_0
  - contourpy=1.3.3=py313h214f63a_0
  - cookiecutter=2.6.0=py313haa95532_1
  - cpp-expected=1.1.0=h214f63a_0
  - cryptography=46.0.3=py313habbc9f9_0
  - cssselect=1.2.0=py313haa95532_0
  - curl=8.16.0=h39d6c2b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dask=2025.11.0=py313haa95532_0
  - dask-core=2025.11.0=py313haa95532_0
  - datashader=0.18.2=py313haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py313h885b0b7_1
  - decorator=5.2.1=py313haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.4.0=py313haa95532_0
  - distributed=2025.11.0=py313haa95532_0
  - distro=1.9.0=py313haa95532_0
  - docstring-to-markdown=0.17=py313haa95532_0
  - docutils=0.21.2=py313haa95532_1
  - et_xmlfile=2.0.0=py313haa95532_0
  - evalidate=2.0.3=py313haa95532_0
  - executing=2.2.1=py313haa95532_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py313haa95532_0
  - flake8=7.1.1=py313haa95532_0
  - flask=3.1.2=py313haa95532_0
  - fmt=11.2.0=h58b7f6e_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py313h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozendict=2.4.6=py313h02ab6af_0
  - frozenlist=1.8.0=py313h885b0b7_0
  - fsspec=2025.10.0=py313h4442805_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=py313haa95532_0
  - gitpython=3.1.45=py313haa95532_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py313h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - greenlet=3.2.4=py313h885b0b7_0
  - h11=0.16.0=py313haa95532_1
  - h5py=3.15.1=py313he283ef2_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.22.0=py313haa95532_0
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_1
  - hvplot=0.12.1=py313haa95532_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py313haa95532_0
  - imageio=2.37.2=py313h4442805_0
  - imagesize=1.4.1=py313haa95532_0
  - imbalanced-learn=0.14.0=py313haa95532_0
  - importlib-metadata=8.7.0=py313haa95532_0
  - incremental=24.7.2=pyhd3eb1b0_0
  - inflection=0.5.1=py313haa95532_1
  - iniconfig=2.1.0=py313haa95532_0
  - intake=2.0.8=py313haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.31.0=py313h4442805_0
  - ipympl=0.9.7=py313haa95532_0
  - ipython=9.7.0=py313haa95532_0
  - ipython_pygments_lexers=1.1.1=py313haa95532_0
  - ipywidgets=8.1.7=py313haa95532_0
  - isort=6.1.0=py313haa95532_0
  - itemadapter=0.12.1=py313haa95532_0
  - itemloaders=1.3.2=py313haa95532_0
  - itsdangerous=2.2.0=py313haa95532_0
  - jaraco.classes=3.4.0=py313haa95532_0
  - jaraco.context=6.0.0=py313haa95532_0
  - jaraco.functools=4.1.0=py313haa95532_0
  - jedi=0.19.2=py313haa95532_0
  - jellyfish=1.2.1=py313h114bc41_0
  - jinja2=3.1.6=py313haa95532_0
  - jmespath=1.0.1=py313haa95532_0
  - joblib=1.5.2=py313haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.12.1=py313haa95532_0
  - jsonpatch=1.33=py313haa95532_1
  - jsonpointer=3.0.0=py313haa95532_0
  - jsonschema=4.25.0=py313haa95532_1
  - jsonschema-specifications=2025.9.1=py313haa95532_0
  - jupyter=1.1.1=py313haa95532_0
  - jupyter-lsp=2.2.5=py313haa95532_0
  - jupyter_client=8.6.3=py313haa95532_1
  - jupyter_console=6.6.3=py313haa95532_1
  - jupyter_core=5.8.1=py313haa95532_0
  - jupyter_events=0.12.0=py313haa95532_0
  - jupyter_server=2.16.0=py313haa95532_0
  - jupyter_server_terminals=0.5.3=py313haa95532_0
  - jupyterlab=4.4.7=py313haa95532_0
  - jupyterlab-variableinspector=3.2.4=py313haa95532_0
  - jupyterlab_pygments=0.3.0=py313haa95532_0
  - jupyterlab_server=2.28.0=py313haa95532_0
  - jupyterlab_widgets=3.0.15=py313haa95532_0
  - keyring=25.7.0=py313haa95532_0
  - kiwisolver=1.4.9=py313h03f52e7_0
  - lazy_loader=0.4=py313haa95532_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libarchive=3.8.2=h6c023e8_0
  - libavif=1.3.0=h5bd13ec_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libclang13=20.1.8=default_hccbf073_0
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - liblief=0.16.4=h96dcfd1_1
  - libllvm20=20.1.8=h3aa9ab2_0
  - libmamba=2.3.2=hc213065_1
  - libmambapy=2.3.2=py313h364efb6_1
  - libmpdec=4.0.0=h827c3e9_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=h83e8143_0
  - libsolv=0.7.30=h23a355e_2
  - libspatialindex=1.9.3=h6c2663c_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.7.1=h3a18249_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=hd1fac9c_0
  - libzlib=1.3.1=h02ab6af_0
  - linkify-it-py=2.0.3=py313haa95532_0
  - llvmlite=0.45.1=py313hd5b4e5d_0
  - locket=1.0.0=py313haa95532_0
  - lsprotocol=2025.0.0=py313haa95532_0
  - lxml=5.3.0=py313h985e36a_2
  - lz4=4.4.5=py313hb1efef3_0
  - lz4-c=1.9.4=h2bbff1b_1
  - lzo=2.10=he774522_2
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-patch=2.7.5=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.8=py313haa95532_0
  - markdown-it-py=2.2.0=py313haa95532_1
  - markupsafe=3.0.2=py313h827c3e9_0
  - matplotlib=3.10.6=py313haa95532_1
  - matplotlib-base=3.10.6=py313h26e45b9_1
  - matplotlib-inline=0.2.1=py313haa95532_0
  - mbedtls=3.5.1=h5da7b33_1
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdit-py-plugins=0.5.0=py313haa95532_0
  - mdurl=0.1.2=py313haa95532_0
  - menuinst=2.4.1=py313h885b0b7_1
  - mistune=3.1.2=py313haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - more-itertools=10.8.0=py313haa95532_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpi=1.0=msmpi
  - mpi4py=4.0.3=py313h827c3e9_0
  - mpmath=1.3.0=py313haa95532_0
  - msgpack-python=1.1.1=py313h5da7b33_0
  - msmpi=10.1.1=had4844c_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.7.0=py313h02ab6af_0
  - multipledispatch=1.0.0=py313haa95532_0
  - mypy=1.17.1=py313h02ab6af_1
  - mypy_extensions=1.0.0=py313haa95532_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - narwhals=2.7.0=py313haa95532_0
  - navigator-updater=0.6.0=py313haa95532_0
  - nbclient=0.10.2=py313haa95532_0
  - nbconvert=7.16.6=py313haa95532_0
  - nbconvert-core=7.16.6=py313haa95532_0
  - nbconvert-pandoc=7.16.6=py313haa95532_0
  - nbformat=5.10.4=py313haa95532_0
  - nest-asyncio=1.6.0=py313haa95532_0
  - networkx=3.5=py313haa95532_0
  - nlohmann_json=3.11.2=h6c2663c_0
  - nltk=3.9.2=py313h63c8d5c_0
  - notebook=7.4.5=py313haa95532_0
  - notebook-shim=0.2.4=py313haa95532_0
  - numba=0.62.1=py313hf6ff4c0_0
  - numexpr=2.14.1=py313h7660c64_0
  - numpy=2.3.5=py313h050da96_0
  - numpy-base=2.3.5=py313h1e017a8_0
  - numpydoc=1.9.0=py313haa95532_0
  - openjpeg=2.5.4=h56d5a42_1
  - openpyxl=3.1.5=py313h827c3e9_1
  - openssl=3.0.18=h543e019_0
  - orc=2.2.0=hf43e1a1_0
  - overrides=7.7.0=py313haa95532_0
  - packaging=25.0=py313haa95532_1
  - pandas=2.3.3=py313h42c1672_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py313haa95532_0
  - panel=1.8.3=py313haa95532_0
  - param=2.3.0=py313haa95532_0
  - parsel=1.10.0=py313haa95532_0
  - parso=0.8.5=py313haa95532_0
  - partd=1.4.2=py313haa95532_0
  - pathspec=0.12.1=py313haa95532_1
  - patsy=1.0.1=py313haa95532_0
  - pcre2=10.46=h5740b90_0
  - pexpect=4.9.0=py313haa95532_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=12.0.0=py313h4212202_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - pkce=1.0.3=py313haa95532_0
  - pkginfo=1.12.0=py313haa95532_0
  - platformdirs=4.5.0=py313haa95532_0
  - plotly=6.3.0=py313h4442805_0
  - pluggy=1.5.0=py313haa95532_0
  - prometheus_client=0.21.1=py313haa95532_0
  - prompt-toolkit=3.0.52=py313haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py313h827c3e9_0
  - protego=0.4.0=py313haa95532_0
  - protobuf=5.29.3=py313h5da7b33_0
  - psutil=7.0.0=py313h02ab6af_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py313haa95532_0
  - py-cpuinfo=9.0.0=py313haa95532_0
  - py-lief=0.16.4=py313h96dcfd1_1
  - pyarrow=21.0.0=py313h42c1672_0
  - pyasn1=0.6.1=py313haa95532_0
  - pyasn1-modules=0.4.2=py313haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycares=4.10.0=py313he29e43d_0
  - pycodestyle=2.12.1=py313haa95532_0
  - pycosat=0.6.6=py313h827c3e9_2
  - pycparser=2.23=py313haa95532_0
  - pyct=0.6.0=py313haa95532_0
  - pycurl=7.45.7=py313hf943856_0
  - pydantic=2.12.4=py313haa95532_0
  - pydantic-core=2.41.5=py313h114bc41_1
  - pydantic-settings=2.12.0=py313haa95532_0
  - pydispatcher=2.0.7=py313haa95532_0
  - pydocstyle=6.3.0=py313haa95532_0
  - pyerfa=2.0.1.5=py313h827c3e9_0
  - pyflakes=3.2.0=py313haa95532_0
  - pygithub=2.8.1=py313haa95532_0
  - pygments=2.19.2=py313haa95532_0
  - pyjwt=2.10.1=py313haa95532_0
  - pylint=3.3.8=py313haa95532_0
  - pylint-venv=3.0.3=py313haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.6.0=py313h581ae37_0
  - pyodbc=5.3.0=py313h885b0b7_0
  - pyopenssl=25.3.0=py313h2b78340_0
  - pyparsing=3.2.5=py313haa95532_0
  - pyqt=5.15.11=py313h816affc_0
  - pyqt5-sip=12.17.0=py313h02ab6af_0
  - pyqtwebengine=5.15.11=py313h01f5876_0
  - pyside6=6.9.2=py313h151a370_0
  - pysocks=1.7.1=py313haa95532_1
  - pytables=3.10.2=py313h0217527_2
  - pytest=8.4.2=py313haa95532_0
  - python=3.13.9=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-dotenv=1.1.0=py313haa95532_0
  - python-fastjsonschema=2.21.2=py313haa95532_0
  - python-json-logger=3.2.1=py313haa95532_0
  - python-libarchive-c=5.1=pyhd3eb1b0_0
  - python-lmdb=1.7.5=py313h5823743_0
  - python-lsp-black=2.0.0=py313haa95532_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-ruff=2.3.0=py313haa95532_0
  - python-lsp-server=1.13.1=py313h4442805_0
  - python-slugify=8.0.4=py313haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=2_cp313
  - pytokens=0.3.0=py313haa95532_0
  - pytoolconfig=1.2.6=py313haa95532_0
  - pytz=2025.2=py313haa95532_0
  - pyuca=1.2=py313haa95532_1
  - pyviz_comms=3.0.6=py313haa95532_0
  - pywavelets=1.9.0=py313h02ab6af_0
  - pywin32=311=py313h885b0b7_0
  - pywin32-ctypes=0.2.2=py313haa95532_0
  - pywinpty=2.0.15=py313h72d21ff_0
  - pyyaml=6.0.3=py313hb9a58be_0
  - pyzmq=27.1.0=py313h7149c55_1
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py313haa95532_0
  - qt-main=5.15.2=h8b2cd8b_13
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.4.0=py313haa95532_0
  - qtbase=6.9.2=h06bae2a_5
  - qtconsole=5.7.0=py313haa95532_0
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtpy=2.4.3=py313haa95532_0
  - qtshadertools=6.9.2=heb02b0b_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebengine=6.9.2=hebbe641_0
  - qtwebsockets=6.9.2=heb02b0b_1
  - queuelib=1.8.0=py313haa95532_0
  - re2=2024.07.02=h214f63a_0
  - readchar=4.2.1=py313haa95532_0
  - referencing=0.37.0=py313haa95532_0
  - regex=2025.9.1=py313h02ab6af_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.5=py313haa95532_1
  - requests-file=2.1.0=py313haa95532_0
  - requests-toolbelt=1.0.0=py313haa95532_0
  - rfc3339-validator=0.1.4=py313haa95532_0
  - rfc3986-validator=0.1.1=py313haa95532_0
  - rich=14.2.0=py313haa95532_0
  - roman-numerals-py=3.1.0=py313haa95532_0
  - rope=1.14.0=py313haa95532_0
  - rpds-py=0.28.0=py313h114bc41_0
  - rtree=1.4.1=py313h873b684_0
  - ruamel.yaml=0.18.16=py313hb9a58be_0
  - ruamel.yaml.clib=0.2.14=py313hb9a58be_0
  - ruamel_yaml=0.17.21=py313h827c3e9_0
  - ruff=0.12.0=py313h1361809_0
  - s3fs=2025.10.0=py313haa95532_0
  - scikit-image=0.25.2=py313hce38976_0
  - scikit-learn=1.7.2=py313h7f7e138_0
  - scipy=1.16.3=py313hbd6d557_0
  - scrapy=2.13.3=py313haa95532_0
  - seaborn=0.13.2=py313haa95532_3
  - semver=3.0.4=py313haa95532_0
  - send2trash=1.8.2=py313haa95532_1
  - service_identity=24.2.0=py313haa95532_0
  - setuptools=80.9.0=py313haa95532_0
  - shellingham=1.5.4=py313haa95532_0
  - simdjson=3.10.1=h214f63a_0
  - sip=6.12.0=py313h706e071_0
  - six=1.17.0=py313haa95532_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.0=py313haa95532_0
  - snowballstemmer=3.0.1=py313haa95532_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py313haa95532_0
  - sphinx=8.2.3=py313h827c3e9_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=6.1.0=py313h2ba046a_2
  - spyder-kernels=3.1.1=py313h4442805_0
  - sqlalchemy=2.0.43=py313hda9a48d_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py313haa95532_0
  - statsmodels=0.14.5=py313h2cb717b_0
  - streamlit=1.51.0=py313haa95532_0
  - superqt=0.7.6=py313hc83c3f3_0
  - sympy=1.14.0=py313haa95532_0
  - tabulate=0.9.0=py313haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tblib=3.1.0=py313haa95532_0
  - tenacity=9.1.2=py313haa95532_0
  - terminado=0.18.1=py313haa95532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=py313h4442805_1
  - threadpoolctl=3.5.0=py313h4442805_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2025.10.4=py313haa95532_0
  - tinycss2=1.4.0=py313haa95532_0
  - tk=8.6.15=hf199647_0
  - tldextract=5.1.2=py313haa95532_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.2.1=py313haa95532_0
  - tomlkit=0.13.3=py313haa95532_0
  - toolz=1.0.0=py313haa95532_0
  - tornado=6.5.1=py313h827c3e9_0
  - tqdm=4.67.1=py313h4442805_1
  - traitlets=5.14.3=py313haa95532_0
  - truststore=0.10.1=py313haa95532_1
  - twisted=25.5.0=py313haa95532_0
  - twisted-iocpsupport=1.0.2=py313h827c3e9_1
  - typer=0.17.4=py313haa95532_1
  - typing-extensions=4.15.0=py313haa95532_0
  - typing-inspection=0.4.2=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - uc-micro-py=1.0.3=py313haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - ujson=5.11.0=py313h885b0b7_0
  - urllib3=2.5.0=py313haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - w3lib=2.3.1=py313haa95532_0
  - watchdog=6.0.0=py313haa95532_0
  - wcwidth=0.2.13=py313haa95532_0
  - webencodings=0.5.1=py313haa95532_2
  - websocket-client=1.8.0=py313haa95532_0
  - werkzeug=3.1.3=py313haa95532_0
  - whatthepatch=1.0.7=py313haa95532_0
  - wheel=0.45.1=py313haa95532_0
  - widgetsnbextension=4.0.14=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - winloop=0.3.1=py313h913537a_0
  - winpty=0.4.3=4
  - wrapt=1.17.0=py313h827c3e9_0
  - xarray=2025.10.1=py313haa95532_0
  - xlwings=0.33.15=py313hd0375be_0
  - xyzservices=2025.4.0=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.8.0=hd77b12b_1
  - yapf=0.43.0=py313haa95532_0
  - yarl=1.22.0=py313h02ab6af_0
  - zeromq=4.3.5=h6c54ac7_1
  - zict=3.0.0=py313haa95532_0
  - zipp=3.23.0=py313haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zlib-ng=2.0.7=h2bbff1b_0
  - zope=1.0=py313haa95532_1
  - zope.interface=8.0.1=py313h02ab6af_0
  - zstandard=0.24.0=py313he335c29_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\ProgramData\anaconda3
